package com.klay.mapper;

import com.klay.model.Question;
import com.klay.model.QuestionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Tue Dec 21 16:40:06 GMT+08:00 2021
     */
    int incView(Question record);
}