CREATE TABLE QUESTION
(
    ID            INT AUTO_INCREMENT,
    CREATOR       INT,
    TITLE         VARCHAR(50),
    DESCRIPTION   TEXT,
    TAG           VARCHAR(256),
    COMMENT_COUNT INT DEFAULT 0,
    VIEW_COUNT    INT DEFAULT 0,
    LIKE_COUNT    INT DEFAULT 0,
    CONSTRAINT QUESTION_PK
        PRIMARY KEY (ID)
);